### ISSUE TITLE
JSONObject could support the path that like "data.user.name".

### ISSUE THREAD

**Issue by arden** [Ikiga/IkigaJSON#2]
```
var json = try JSONObject()
json["data.user.name"]
```

JSONObject could support the path that like "data.user.name".

**Comment by Joannis** [comment]
Not using the normal subscript. It wouldn't be a normal use case, but you can have an object like this:

```json
{
    "user.name": "Joannis"
}
```

It's a good idea to keep in mind, though. For now you can do `json["data"]["user"]["name"]`
